# Generated by Django 5.0.6 on 2024-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_lyricspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricspage',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
