# Generated by Django 5.0.6 on 2024-07-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_lyricspage_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('song_title', models.CharField(max_length=255)),
                ('lyrics', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='LyricsPage',
        ),
    ]
