# Generated by Django 5.0.6 on 2024-07-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_quizquestion_delete_lyricspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='song_title',
            new_name='title',
        ),
    ]
