# Generated by Django 5.0.6 on 2024-07-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_artist_artistpage_delete_artistepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('paroles', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
