# Generated by Django 5.0.6 on 2024-07-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_artistepage_delete_chanson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistePage',
        ),
    ]
